services:
    json_schema.controller:
        class: Knp\JsonSchemaBundle\Controller\SchemaController
        public: true
        arguments:
            - '@json_schema.registry'
            - '@json_schema.generator'
            - '@router'

    json_schema.generator:
        class: Knp\JsonSchemaBundle\Schema\SchemaGenerator
        arguments:
            - '@router'
            - '@json_schema.reflection_factory'
            - '@json_schema.registry'
            - '@json_schema.factory.schema'
            - '@json_schema.factory.property'

    json_schema.registry:
        public: true
        class: Knp\JsonSchemaBundle\Schema\SchemaRegistry

    json_schema.factory.schema:
        public: false
        class: Knp\JsonSchemaBundle\Model\SchemaFactory

    json_schema.factory.property:
        public: false
        class: Knp\JsonSchemaBundle\Model\PropertyFactory

    json_schema.reflection_factory:
        public: false
        class: Knp\JsonSchemaBundle\Reflection\ReflectionFactory
        arguments:
            - '@json_schema.finder'
            - '@json_schema.filesystem'

    json_schema.finder:
        public: false
        class: Symfony\Component\Finder\Finder

    json_schema.filesystem:
        public: false
        class: Symfony\Component\Filesystem\Filesystem

    json_schema.response.factory:
        class: Knp\JsonSchemaBundle\HttpFoundation\JsonResponseFactory
        arguments:
            - '@json_schema.registry'
            - '@router'

    # validator.mapping.class_metadata_factory is also used for
    # Symfony\Component\Form\FormTypeGuesserInterface\ValidatorTypeGuesser
    # so we decorate it in order for our FormTypeGuesserHandler to support
    # traits as well.
    # In the container, the original LazyLoadingMetadataFactory is created
    # from the factory method Symfony\Component\Validator\ValidatorBuilder::getValidator()
    # which does not inject its loader chain into the container.
    # Fortunately, the ValidatorBuilder exposes a public getLoaders() method
    # we can call to fetch and re-inject the exact same loaders into a
    # brand-new LoaderChain.
    json_schema.bridge.lazy_loading_metadata_factory:
        class: Knp\JsonSchemaBundle\Bridge\TraitAwareLazyLoadingMetadataFactory
        decorates: validator.mapping.class_metadata_factory
        arguments:
            - '@json_schema.bridge.lazy_loading_metadata_factory.inner'
            - !service
                class: Symfony\Component\Validator\Mapping\Loader\LoaderChain
                arguments:
                    - "@=service('validator.builder').getLoaders()"

    # Contrary to validator's LazyLoadingMetadataFactory, the serializer's
    # loader chain is exposed directly to the container.
    json_schema.bridge.class_metadata_factory:
        class: Knp\JsonSchemaBundle\Bridge\TraitAwareClassMetadataFactory
        decorates: serializer.mapping.class_metadata_factory
        arguments:
            - '@json_schema.bridge.class_metadata_factory.inner'
            - '@serializer.mapping.chain_loader'

    json_schema.property.handler.annotation:
        public: false
        class: Knp\JsonSchemaBundle\Property\JsonSchemaAnnotationHandler
        arguments:
            - '@annotation_reader'
            - '@json_schema.reflection_factory'
        tags:
            - { name: json_schema.property.handler, priority: 0 }

    json_schema.property.handler.chained_guesser:
        public: false
        class: Knp\JsonSchemaBundle\Property\FormTypeGuesserHandler
        arguments:
            - '@form.chain.guesser'
            - '@json_schema.registry'
        tags:
            - { name: json_schema.property.handler, priority: 10 }

    json_schema.property.handler.extra_validator_constraints_handler:
        public: false
        class: Knp\JsonSchemaBundle\Property\ExtraValidatorConstraintsHandler
        arguments:
            - '@validator.mapping.class_metadata_factory'
        tags:
            - { name: json_schema.property.handler, priority: 20 }

    json_schema.property.handler.doctrine_reflection_handler:
        public: false
        class: Knp\JsonSchemaBundle\Property\DoctrineReflectionConstraintsHandler
        arguments:
            - '@doctrine.orm.default_entity_manager'
        tags:
            - { name: json_schema.property.handler, priority: 30 }

    json_schema.property.handler.serializer_reflection_handler:
        public: false
        class: Knp\JsonSchemaBundle\Property\SerializerReflectionConstraintsHandler
        arguments:
            - '@serializer.mapping.class_metadata_factory'
        tags:
            - { name: json_schema.property.handler, priority: 40 }

    json_schema.property.handler.php_reflection_handler:
        public: false
        class: Knp\JsonSchemaBundle\Property\PhpReflectionTypedPropertiesHandler
        tags:
            - { name: json_schema.property.handler, priority: 50 }

    form.chain.guesser:
        public: false
        class: Symfony\Component\Form\FormTypeGuesserChain
        arguments:
            - ['@form.type_guesser.validator', '@json_schema.guesser']
